package com.fishe.wut2dodemo;

import android.app.Activity;
import android.content.Context;
import android.content.IntentSender;
import android.location.Location;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.util.Log;

import com.google.android.gms.common.ConnectionResult;
import com.google.android.gms.common.api.GoogleApiClient;
import com.google.android.gms.location.LocationListener;
import com.google.android.gms.location.LocationRequest;
import com.google.android.gms.location.LocationServices;

/**
 * LocationGenerator generates the user's location by using Google Location API.
 */
public class LocationGenerator implements
        GoogleApiClient.ConnectionCallbacks,
        GoogleApiClient.OnConnectionFailedListener,
        LocationListener {

    private static final int DEFAULT_INTERVAL = 10 * 1000;
    private static final int DEFAULT_FASTEST_INTERVAL = 5 * 1000;
    private static final int CONNECTION_FAILURE_RESOLUTION_REQUEST = 9999;
    private static final int HALF_SECOND = 500;
    private static final String TAG = LocationGenerator.class.getSimpleName();

    private GoogleApiClient mGoogleApiClient;
    private LocationRequest mLocationRequest;
    private final LocationUpdate mLocationUpdate;
    private final Activity mActivity;
    private boolean isLocationGenerated;

    /**
     * Used to lock the thread in place while waiting for GoogleApiClient to finish connection.
     */
    private static final Object mLocationLock = new Object();

    /**
     * LocationUpdate allows classes to update user location based on the location generated by
     * LocationGenerator.
     */
    interface LocationUpdate {
        void updateLocation(Location location);
    }

    /**
     * Initialises the necessary components to generate user's location.
     * @param activity          The Activity that called this constructor.
     * @param locationUpdate    The Activity implementing LocationUpdate that called this constructor.
     */
    LocationGenerator(Activity activity, LocationUpdate locationUpdate) {
        Log.i(TAG, "Initialising LocationGenerator.");
        initialiseGoogleApiClient(activity);
        createLocationRequest();
        mLocationUpdate = locationUpdate;
        mActivity = activity;
        isLocationGenerated = false;
    }

    /**
     * Initialises and connects GoogleApiClient.
     * @param context   The Context that called this method.
     */
    private void initialiseGoogleApiClient(Context context) {
        assert context != null;

        mGoogleApiClient = new GoogleApiClient.Builder(context)
                .addConnectionCallbacks(this)
                .addOnConnectionFailedListener(this)
                .addApi(LocationServices.API)
                .build();
        mGoogleApiClient.connect();
    }

    /**
     * Sets the accuracy of generating user location and the interval of updating
     * the location of user location to default values.
     */
    private void createLocationRequest() {
        if (mLocationRequest == null) {
            mLocationRequest = new LocationRequest();
            mLocationRequest.setInterval(DEFAULT_INTERVAL);
            mLocationRequest.setFastestInterval(DEFAULT_FASTEST_INTERVAL);
            mLocationRequest.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);
        }
    }

    /**
     * Automatically called when GoogleApiClient connection is suspended temporarily.
     * It will try to automatically resolve by reconnecting GoogleApiClient if possible.
     * @param cause Reason for disconnection.
     */
    @Override
    public void onConnectionSuspended(int cause) {
        Log.i("TAG", "GoogleApiClient connection suspended with code: " + cause);
    }

    /**
     * Automatically called when GoogleApiClient fails to connect to Google servers.
     * It will try to automatically resolve by reconnecting GoogleApiClient if possible.
     * @param result    A ConnectionResult that can be used for resolving the error,
     *                  and deciding what sort of error occurred.
     */
    @Override
    public void onConnectionFailed(@NonNull ConnectionResult result) {
        Log.i("TAG", "GoogleApiClient failed to connect.");

        if (result.hasResolution()) {
            try {
                result.startResolutionForResult(mActivity, CONNECTION_FAILURE_RESOLUTION_REQUEST);
            } catch (IntentSender.SendIntentException e) {
                Log.i(TAG, e.getMessage());
            }
        } else {
            Log.i(TAG, "Location services connection failed with code: " + result.getErrorCode());
        }
    }

    /**
     * Called after trying to resolve unsuccessful connection of GoogleApiClient.
     * @param requestCode   Identifier for the request that was made.
     * @param resultCode    Integer value of result for the activity.
     */
    public void onCallerActivityResult(int requestCode, int resultCode) {
        switch (requestCode) {
            case CONNECTION_FAILURE_RESOLUTION_REQUEST:
                switch (resultCode) {
                    case Activity.RESULT_OK:
                        Log.i(mActivity.getLocalClassName(), "GoogleApiClient resolution success.");
                        break;
                    case Activity.RESULT_CANCELED:
                        Log.i(mActivity.getLocalClassName(), "GoogleApiClient resolution unsuccessful.");
                        break;
                    default:
                        Log.i(mActivity.getLocalClassName(), "GoogleApiClient resolution went wrong.");
                        break;
                }
                break;
        }
    }

    /**
     * Automatically called upon GoogleApiClient successful connection.
     * It will begin to request for location updates.
     */
    @Override
    public void onConnected(Bundle bundle) {
        assert mLocationLock != null;

        Log.i(TAG, "GoogleApiClient connected.");
        try {
            retrievePreviousLocationIfAvailable();
            LocationServices.FusedLocationApi.requestLocationUpdates(
                    mGoogleApiClient, mLocationRequest, this);
        } catch (SecurityException se) {
            Log.i(TAG, "Security Exception caught: " + se.getMessage());
        }
    }

    /**
     * Retrieves the user's last known location if available,
     * to get the app continue functioning while waiting for newer location updates which
     * can take longer time.
     */
    private void retrievePreviousLocationIfAvailable() {
        try {
            Location location = LocationServices.FusedLocationApi.getLastLocation(mGoogleApiClient);
            if (location != null) {
                Log.i(TAG, "Able to detect user's previous location.");
                isLocationGenerated = true;
                mLocationUpdate.updateLocation(location);
            }
        } catch (SecurityException se) {
            Log.i(TAG, "Security Exception caught: " + se.getMessage());
        }
    }

    /**
     * Generates a Runnable that sleeps the thread it is currently on until location is generated.
     * @return  Runnable that sleeps the thread it is currently on until location is generated.
     */
    Runnable generateUnlockRunnable() {
        return new Runnable() {
            @Override
            public void run() {
                while (!isLocationGenerated) {
                    sleepThread(HALF_SECOND);
                }
                unlockLocationLockThread();
            }
        };
    }

    private void sleepThread(int milliseconds) {
        try {
            Thread.sleep(milliseconds);
        } catch (InterruptedException ie) {
            Log.i(TAG, ie.getMessage());
        }
    }

    /**
     * Unlocks the running thread that is locked while waiting for user location to be generated.
     */
    private void unlockLocationLockThread() {
        assert mLocationLock != null;

        synchronized (mLocationLock) {
            mLocationLock.notifyAll();
        }
    }

    /**
     * Generates a Runnable that locks the thread it is currently on until location is generated,
     * before running @param runnable in UI thread.
     * @param runnable  The operations to be run in UI thread after location is generated.
     * @return          Runnable that locks the thread it is currently on until location is generated,
     *                  before running @param runnable in UI thread.
     */
    @NonNull
    Runnable generateLockRunnable(final Runnable runnable) {
        return new Runnable() {
            @Override
            public void run() {
                lockThreadUntilLocationIsGenerated();
                mActivity.runOnUiThread(runnable);
            }
        };
    }

    /**
     * Locks the running thread until user location is generated, so that activities that
     * require user location will not get NullPointerException.
     */
    void lockThreadUntilLocationIsGenerated() {
        assert mLocationLock != null;

        synchronized (mLocationLock) {
            while (!isLocationGenerated) {
                try {
                    Log.i(TAG, "Waiting for location to be generated.");
                    mLocationLock.wait();
                } catch (InterruptedException ie) {
                    Log.i(TAG, "InterruptedException caught.");
                }
            }
        }
    }

    /**
     * Updates user's location when the user moves around. Automatically called when user' location
     * changes.
     * @param location  User's new location.
     */
    @Override
    public void onLocationChanged(Location location) {
        isLocationGenerated = true;
        mLocationUpdate.updateLocation(location);
    }

    /**
     * Reconnects GoogleApiClient and request for location updates.
     */
    void resumeLocationUpdates() {
        if (!mGoogleApiClient.isConnected() && !mGoogleApiClient.isConnecting()) {
            Log.i(TAG, "Resuming GoogleApiClient connection.");
            mGoogleApiClient.connect();
        }
    }

    void pauseLocationUpdates() {
        Log.i(TAG, "Pausing GoogleApiClient connection.");
        LocationServices.FusedLocationApi.removeLocationUpdates(mGoogleApiClient, this);
    }

    void stopLocationUpdates() {
        Log.i(TAG, "Stopping GoogleApiClient connection.");
        mGoogleApiClient.disconnect();
    }

    GoogleApiClient getGoogleApiClient() { return mGoogleApiClient; }
    LocationRequest getLocationRequest() { return mLocationRequest; }
}
